on:
  issues:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create local changes
      uses: lloydtao/profile-readme-guestbook@main
      with:
        path: $GITHUB_WORKSPACE
        user: ${{ github.event.issue.issue.title }}
        message: ${{ github.event.issue.issue.user.login }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
